FROM oven/bun:alpine

WORKDIR /home/app

ARG DATABASE_URL

COPY package.json bun.lock turbo.json ./

# Maintaining Directory Structure
COPY apps/api-server/package.json ./apps/api-server/
COPY apps/reverse-proxy/package.json ./apps/reverse-proxy/
COPY apps/web/package.json ./apps/web/
COPY packages/prismaDB/package.json ./packages/prismaDB/
COPY packages/eslint/package.json ./packages/eslint/
COPY packages/typescript-config/package.json ./packages/typescript-config/

#Install deps
RUN bun install

#Pass the DB url while building the docker image of nextJS project bcz it needs to talk to the DB(Server Side Rendering)
# If you don't provide it the building pipe line will fail

# Copy source code
COPY packages ./packages
COPY apps/web ./apps/web

# Install openssl on alpine
RUN apk add --no-cache openssl

RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

# Command to run the backend
CMD [ "bun","run","start:web" ]